apiVersion: v1
kind: Service
metadata:
  name: rapidrtmp
  labels:
    app: rapidrtmp
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: rtmp
    port: 1935
    targetPort: 1935
    protocol: TCP
  selector:
    app: rapidrtmp

